name: release
on:
  status:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Verify Jenkins status
      run: |
        # May seem more efficient to just check $GITHUB_EVENT_PATH when $GITHUB_EVENT_NAME = status,
        # but this has a race condition: an older commit goes green, the workflow is triggered,
        # and then we deploy a newer commit! So verify the status for $GITHUB_SHA in all cases.
        curl -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -s $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/statuses | \
          jq -e '.[] | select(.context == "continuous-integration/jenkins/branch" and .state == "success")'
    - name: Check out
      uses: actions/checkout@v1
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Release
      run: bash .github/workflows/release.sh
      env:
        ARTIFACTORY_TOKEN: ${{ secrets.ARTIFACTORY_TOKEN }}
